"""Initial migration

Revision ID: 367e3226ba05
Revises: 
Create Date: 2024-08-29 13:55:47.611165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367e3226ba05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=False),
    sa.Column('services', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('generated_content', sa.Text(), nullable=True),
    sa.Column('generated_picture', sa.String(length=200), nullable=True),
    sa.Column('generated_voice', sa.String(length=200), nullable=True),
    sa.Column('generated_music', sa.String(length=200), nullable=True),
    sa.Column('generated_video', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    # ### end Alembic commands ###
